name: Build Double Dash Deluxe

on: [push, pull_request]

jobs:
  build-linux:
    name: Build on Linux
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Wine
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install wine32
          WINEARCH=win32 winecfg
      - name: Install Ninja
        run: sudo apt-get install ninja-build
      - name: Install LLD
        run: |
          sudo apt-get install lld-15
          sudo update-alternatives --install /usr/bin/ld.lld ld.lld /usr/bin/ld.lld-15 15
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install pyelftools
        run: pip install pyelftools
      - name: Cache CodeWarrior
        id: cache-cw
        uses: actions/cache@v3
        with:
          path: cache
          key: ${{ runner.os }}-cw-se-v2.10
      - name: Download CodeWarrior
        if: steps.cache-cw.outputs.cache-hit != 'true'
        run: |
          mkdir cache && cd cache
          wget "https://www.nxp.com/lgfiles/devsuites/PowerPC/CW55xx_v2_10_SE.exe"
          cd ..
      - name: Prepare tools
        run: bash tools/prepare.sh cache/CW55xx_v2_10_SE.exe
      - name: Build
        run: python build.py --ci
      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: ddd-linux
          path: out

  format-linux:
    name: Format on Linux
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install clang-format
        run: sudo apt-get install clang-format-15
      - name: Format
        run: |
          dirs="common libc loader payload"
          find $dirs -regex '.*\.\(c\|h\|cc\|hh\)' | xargs clang-format-15 --dry-run -Werror
